name = "veloxfusiontop"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "35.198.217.130"
UUID = "35f8c756-76d1-480a-bd82-6b658ff57f83"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
