name = "veloxfusiontop"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "35.198.217.130"
UUID = "4a59970d-9d59-45c9-976c-771b591d8be3"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
